language: objective-c
osx_image: xcode10
before_install:
  - gem install cocoapods -v '1.5.0'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis --no-rdoc --no-ri
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build -workspace Example/Skylark.xcworkspace -scheme Skylark-Example -destination "platform=iOS Simulator,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - pod lib lint